### ISSUE TITLE
Best way to save and load a validator function?

### ISSUE THREAD

**Issue by anderslaunerbaek** [ropensci/jsonvalidate#6]
Hi there,

What is the best way to save the validator function for later use? 
It returns: Error in context_eval(join(src), private$context) : ReferenceError: jv_21774e4676e1 is not defined  when I try to use a saved validator function.

Thanks 

/Anders

**Comment by colearendt** [comment]
At present, the way the validator works is by creating a temp file:
```r
 name <- basename(tempfile("jv_"))
```

So you are correct that saving the R object does not help because the temp file can be lost, and then the validator does not have anything to execute (In your example, the temp file `jv_21774e4676e1` is missing).  The easiest approach at present is to just save the schema, because a new validator can always be created on the fly.  However, perhaps worth thinking about a way to make the validator function an R object.
